---
title: "About"
---

```{r}
#| label: ohp-slides
#| echo: false
#| results: asis
s_ohp_url <- "https://charlotte-ngs.github.io/asmasss2024/ohp/"
s_ex_url <- "https://charlotte-ngs.github.io/asmasss2024/exercises/"
s_sol_url <- "https://charlotte-ngs.github.io/asmasss2024/solutions/"
s_sl_url <- "https://charlotte-ngs.github.io/asmasss2024/slides/"
s_cn_url <- "https://charlotte-ngs.github.io/asmasss2024/cn/"
s_data_url <- "https://charlotte-ngs.github.io/asmasss2024/data/"
s_app_url <- s_cn_url
```

# asmas -- ss2024: Week 9

## asmasss2024 0.9.3

* Course notes [04_mlem](`r paste0(s_cn_url, "04_mlem.pdf", collapse = "")`)

## asmasss2024 0.9.2

* Data for simulation [asm_bw_bc_reg](`r paste0(s_data_url, "asm_bw_bc_reg.csv", collapse = "")`)
* Data on interactions [asm_bw_flem](`r paste0(s_data_url, "asm_bw_flem.csv", collapse = "")`)

## asmasss2024 0.9.1

* Slides on simulation [l07_simulation](`r paste0(s_sl_url, "l07_simulation/l07_simulation.pdf", collapse = "")`)

## asmasss2024 0.9.0

* Slides on interactions [l06_interactions](`r paste0(s_sl_url, "l06_interactions/l06_interactions.pdf", collapse = "")`)


# asmas -- ss2024: Week 8

## asmasss2024 0.8.1

* Overhead [ohp_l08](`r paste0(s_ohp_url, "20240415_ohp_l08.pdf", collapse = "")`)

## asmasss2024 0.8.0

* Exercise on contrasts [asm_ex07](`r paste0(s_ex_url, "asm_ex07/asm_ex07.html", collapse = "")`)
* Exercise on fixed linear effects model [asm_ex06](`r paste0(s_ex_url, "asm_ex06/asm_ex06.html", collapse = "")`)


# asmas -- ss2024: Week 7

## asmasss2024 0.7.2

* Overhead [ohp_l07](`r paste0(s_ohp_url, "20240408_ohp_l07.pdf", collapse = "")`)

## asmasss2024 0.7.1

* Data set on [estimable functions](`r paste0(s_data_url, "est_fun_breed_data.csv", collapse = "")`)
* Exercise on genomic regression [asm_ex05](`r paste0(s_ex_url, "asm_ex05/asm_ex05.html", collapse = "")`)
* Solutions on genomic regression [asm_sol05](`r paste0(s_sol_url, "asm_sol05/asm_sol05.html", collapse = "")`)

## asmasss2024 0.7.0

* Corrections of course notes [chapter 3](`r paste0(s_cn_url, "flem.pdf", collapse = "")`)

# asmas -- ss2024: Week 6

## asmasss2024 0.6.1

* Overhead [ohp_l06](`r paste0(s_ohp_url, "20240325_ohp_l06.pdf", collapse = "")`)

## asmasss2024 0.6.0

* Slides on estimable functions [l04_est_fun](`r paste0(s_sl_url, "l04_est_fun/l04_est_fun.pdf", collapse = "")`)

# asmas -- ss2024: Week 5

## asmasss2024 0.5.3

* Overhead [ohp_l05](`r paste0(s_ohp_url, "20240318_ohp_l05.pdf", collapse = "")`)

## asmasss2024 0.5.2

* Solution [asm_sol04](`r paste0(s_sol_url, "asm_sol04/asm_sol04.html", collapse = "")`)

## asmasss2024 0.5.1

* Exercise [asm_ex04](`r paste0(s_ex_url, "asm_ex04/asm_ex04.html", collapse = "")`)
* Slides on fixed linear effects models [l03_flem](`r paste0(s_sl_url, "l03_flem/l03_flem.pdf", collapse = "")`)

## asmasss2024 0.5.0

* Chapter 3.6 on [Interactions](`r paste0(s_cn_url, "interactions.pdf", collapse = "")`)

# asmas -- ss2024: Week 4

## asmasss2024 0.4.4

* Overhead [ohp_l04](`r paste0(s_ohp_url, "20240311_ohp_l04.pdf", collapse = "")`)

## asmasss2024 0.4.3

* Solutions [asm_sol03](`r paste0(s_sol_url, "asm_sol03/asm_sol03.html", collapse = "")`)

## asmasss2024 0.4.2

* Course notes [chapter 3](`r paste0(s_cn_url, "flem.pdf", collapse = "")`)

## asmasss2024 0.4.1

* Exercise [asm_ex03](`r paste0(s_ex_url, "asm_ex03/asm_ex03.html", collapse = "")`)

# asmas -- ss2024: Week 3

## asmasss2024 0.3.1

* [OHP-L03](`r paste0(s_ohp_url, "20240304_ohp_l03.pdf", collapse = "")`)


## asmasss2024 0.3.0

* Appendix on [Linear Algebra](`r paste0(s_app_url, "099_Appendix_A_LinAlg.pdf", collapse="")`) 

## asmasss2024 0.2.3

* Slides [l02_lin_regr](`r paste0(s_sl_url, "l02_lin_regr/l02_lin_regr.pdf", collapse = "")`)

## asmasss2024 0.2.2

* Exercise 2: [asm-ex02](`r paste0(s_ex_url, "asm_ex02/asm_ex02.html", collapse = "")`)
* Solutions 1: [html](`r paste0(s_sol_url, "asm_sol01/asm_sol01.html", collapse = "")`) | [pdf](`r paste0(s_sol_url, "asm_sol01/asm_sol01.pdf", collapse = "")`)
* Solutions 2: [html](`r paste0(s_sol_url, "asm_sol02/asm_sol02.html", collapse = "")`) | [pdf](`r paste0(s_sol_url, "asm_sol02/asm_sol02.pdf", collapse = "")`)


# asmas -- ss2024: Week 2

## asmasss2024 0.2.1

* [OHP-L02](`r paste0(s_ohp_url, "20240226_ohp_l02.pdf", collapse = "")`)


## asmas - ss2024: v0.2.0

* [Description](https://charlotte-ngs.github.io/asmasss2024/misc/rexpf/rexpf_docu.html) of R exercise platform
* [Data](https://charlotte-ngs.github.io/asmasss2024/data/asm_width_height.xlsx) as Excel sheet on width and height
* [Data](https://charlotte-ngs.github.io/asmasss2024/data/asm_width_height.csv) as comma separated list


# asmas -- ss2024: Week 1

## asmas - ss2024: v0.1.2

* Overhead pictures of lecture 1

## asmas - ss2024: v0.1.1

* Chapters 1 and 2 of course notes
* Slides for introduction

## asmas - ss2024: v0.1.0

* Set up initial version of website
