---
title: "Additional Information"
---

Further information 

## Slides

```{r}
#| label: table-slides
#| echo: false
#| results: asis
s_sl_url <- "https://charlotte-ngs.github.io/asmasss2024/slides/"
tbl_slides <- tibble::tibble(Nr = c(1, 2, 3, 4, 5),
                         Date = c("2024-02-19",
                                  "2024-02-26",
                                  "2024-03-18",
                                  "2024-03-25",
                                  "2024-04-15"),
                         Topic = c(
                           paste0("[Introduction](", 
                                  s_sl_url, 
                                  "l01_intro/l01_intro.pdf)", 
                                  collapse = ""),
                           paste0("[Linear Regression](",
                                  s_sl_url,
                                  "l02_lin_regr/l02_lin_regr.pdf)",
                                  collapse = ""),
                           paste0("[Fixed Linear Effects Models](",
                                  s_sl_url,
                                  "l03_flem/l03_flem.pdf)",
                                  collapse = ""),
                           paste0("[Estimable Functions](",
                                  s_sl_url,
                                  "l04_est_fun/l04_est_fun.pdf)",
                                  collapse = ""),
                           paste0("[Contrasts](",
                                  s_sl_url,
                                  "l05_contrasts/l05_contrasts.pdf)", collapse = "")
                         ))
knitr::kable(tbl_slides)
```


## Over-Head Pictures

```{r}
#| label: ohp-slides
#| echo: false
#| results: asis
s_ohp_url <- "https://charlotte-ngs.github.io/asmasss2024/ohp/"
tbl_ohp <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8),
                          Date = c("2024-02-19",
                                   "2024-02-26",
                                   "2024-03-04",
                                   "2024-03-11",
                                   "2024-03-18",
                                   "2024-03-25",
                                   "2024-04-08",
                                   "2024-04-15"),
                          Topic = c(
                            paste0("[Introduction](",
                                   s_ohp_url,
                                   "20240219_ohp_l01.pdf)",
                                   collapse = ""),
                            paste0("[Regression Residuals](",
                                   s_ohp_url, 
                                   "20240226_ohp_l02.pdf)",
                                   collapse = ""),
                            paste0("[Derive Regression Line](",
                                   s_ohp_url,
                                   "20240304_ohp_l03.pdf)",
                                   collapse = ""),
                            paste0("[Multiple Linear Regression](",
                                   s_ohp_url,
                                   "20240311_ohp_l04.pdf)",
                                   collapse = ""),
                            paste0("[Fixed Linear Effects Models](",
                                   s_ohp_url,
                                   "20240318_ohp_l05.pdf)",
                                   collapse = ""),
                            paste0("[Least Squares Normal Equations](",
                                   s_ohp_url,
                                   "20240325_ohp_l06.pdf)",
                                   collapse = ""),
                            paste0("[Estimable Functions](",
                                   s_ohp_url,
                                   "20240408_ohp_l07.pdf)",
                                   collapse = ""),
                            paste0("[Contrasts](",
                                   s_ohp_url,
                                   "20240415_ohp_l08.pdf)",
                                   collapse = "")
                          ))
knitr::kable(tbl_ohp)
```


