---
title: "Exercises"
---

List of exercises

```{r}
#| label: exercises
#| echo: false
#| results: asis
s_ex_url <- "https://charlotte-ngs.github.io/asmasss2024/exercises/"
tbl_ex <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                         Date = c("2024-02-19",
                                  "2024-02-26",
                                  "2024-03-11",
                                  "2024-03-18",
                                  "2024-04-08",
                                  "2024-04-15",
                                  "2024-04-15",
                                  "2024-04-29",
                                  "2024-05-06",
                                  "2024-05-13",
                                  "2024-05-20",
                                  "2024-05-20"),
                         Topic = c(
                           paste0("[Introduction](", 
                                  s_ex_url,
                                  "asm_ex01/asm_ex01.html)", 
                                  collapse = ""),
                           paste0("[Read Data](",
                                  s_ex_url,
                                  "asm_ex02/asm_ex02.html)", 
                                  collapse = ""),
                           paste0("[Linear Regression](",
                                  s_ex_url,
                                  "asm_ex03/asm_ex03.html)", 
                                  collapse = ""),
                           paste0("[Matrix-Vector-Notation](",
                                  s_ex_url,
                                  "asm_ex04/asm_ex04.html)", 
                                  collapse = ""),
                           paste0("[Genomic Regression](",
                                  s_ex_url,
                                  "asm_ex05/asm_ex05.html)", 
                                  collapse = ""),
                           paste0("[Fixed Linear Effects Model](",
                                  s_ex_url, 
                                  "asm_ex06/asm_ex06.html)", 
                                  collapse = ""),
                           paste0("[Contrasts](",
                                  s_ex_url,
                                  "asm_ex07/asm_ex07.html)", 
                                  collapse = ""),
                           paste0("[Interactions and Simulation](",
                                  s_ex_url,
                                  "asm_ex08/asm_ex08.html)", 
                                  collapse = ""),
                           paste0("[Repeated Observations](", 
                                  s_ex_url,
                                  "asm_ex09/asm_ex09.html)", 
                                  collapse = ""),
                           paste0("[Test Exam](",
                                  s_ex_url,
                                  "asm_test_exam/asm_exam_tsk.pdf)",
                                  collapse = ""),
                           paste0("[Sire Model](",
                                  s_ex_url,
                                  "asm_ex10/asm_ex10.html)",
                                  collapse = ""),
                           paste0("[Animal Model](",
                                  s_ex_url, 
                                  "asm_ex11/asm_ex11.html)",
                                  collapse = "")
                         ))
knitr::kable(tbl_ex)
```



```{r}
#| label: latest-change
#| echo: false
#| results: asis
cat(rmdhelp::get_latest_change())
```


