---
title: "Solutions"
---

List of solutions to exercises

```{r}
#| label: solutions
#| echo: false
#| results: asis
s_sol_url <- "https://charlotte-ngs.github.io/asmasss2024/solutions/"
tbl_sol <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8, 9),
                         Date = c("2024-02-19",
                                  "2024-02-26",
                                  "2024-03-11",
                                  "2024-03-18",
                                  "2024-04-08",
                                  "2024-04-29",
                                  "2024-04-29",
                                  "2024-05-06",
                                  "2024-05-13"),
                         Topic = c(
                           paste0("Introduction [html](", 
                                  s_sol_url,
                                  "asm_sol01/asm_sol01.html) | [pdf](",
                                  s_sol_url, 
                                  "asm_sol01/asm_sol01.pdf)", 
                                  collapse = ""),
                           paste0("Read Data [html](", 
                                  s_sol_url,
                                  "asm_sol02/asm_sol02.html) | [pdf](",
                                  s_sol_url,
                                  "asm_sol02/asm_sol02.pdf)", 
                                  collapse = ""),
                           paste0("Simple Linear Regression [html](",
                                  s_sol_url,
                                  "asm_sol03/asm_sol03.html) | [pdf](",
                                  s_sol_url,
                                  "asm_sol03/asm_sol03.pdf)", 
                                  collapse = ""),
                           paste0("Matrix-Vector-Notation [html](",
                                  s_sol_url,
                                  "asm_sol04/asm_sol04.html) | [pdf](",
                                  s_sol_url,
                                  "asm_sol04/asm_sol04.pdf)", 
                                  collapse = ""),
                           paste0("Genomic Regression [html](",
                                  s_sol_url,
                                  "asm_sol05/asm_sol05.html) | [pdf](",
                                  s_sol_url,
                                  "asm_sol05/asm_sol05.pdf)", 
                                  collapse = ""),
                           paste0("Fixed Linear Effects Model [html](",
                                  s_sol_url,
                                  "asm_sol06/asm_sol06.html) | [pdf](",
                                  s_sol_url,
                                  "asm_sol06/asm_sol06.pdf)",
                                  collapse = ""),
                           paste0("Contrasts [html](",
                                  s_sol_url,
                                  "asm_sol07/asm_sol07.html) | [pdf](",
                                  s_sol_url,
                                  "asm_sol07/asm_sol07.pdf)",
                                  collapse = ""),
                           paste0("Interactions and Simulation [html](",
                                  s_sol_url,
                                  "asm_sol08/asm_sol08.html) | [pdf](",
                                  s_sol_url,
                                  "asm_sol08/asm_sol08.pdf)",
                                  collapse = ""),
                           paste0("Repeated Observations [html](",
                                  s_sol_url,
                                  "asm_sol09/asm_sol09.html) | [pdf](",
                                  s_sol_url,
                                  "asm_sol09/asm_sol09.pdf)",
                                  collapse = ""),
                           paste0("Test Exam [pdf](",
                                  s_sol_url,
                                  "asm_test_sol/asm_exam_sol.pdf)",
                                  collapse = "")
                         ))
knitr::kable(tbl_sol)
```




```{r}
#| label: latest-change
#| echo: false
#| results: asis
cat(rmdhelp::get_latest_change())
```

