---
title: "Applied Statistical Methods - Solution 9"
author: "Peter von Rohr"
date: 2024-05-06
filters: 
  - webr
webr:
  packages: ['dplyr']
---

## Problem 1: Repeated Observations in Predictors
Use the dataset on blood presure and pulse frequency and fit linear regression models with response variables `SYS`, `DIA` and `PUL` on the mean of the manually measured pulse frequencies. Check the distribution of the residuals with a dot-plot of the resiudals of the regression model on the fitted values. For which of the responses (`SYS`, `DIA` and `PUL`), the highest absolute regression coefficient can be found? The dataset is available at 

```{r data-ex09-p01, echo=FALSE}
s_tbl_ex09_p01_path <- "https://charlotte-ngs.github.io/asmasss2024/data/20240429_bp_data.csv"
s_tbl_ex09_p01_path
```

### Tasks
* Read the data

```{webr-r}
# read data to a data.frame
s_tbl_ex09_p01_path <- "https://charlotte-ngs.github.io/asmasss2024/data/20240429_bp_data.csv"
df_bp <- read.table(s_tbl_ex09_p01_path, header = T, sep = ",")
df_bp
```

* Compute mean of manual pulse frequencies

```{webr-r}
# compute mean values accross individuals
library(dplyr)
tbl_bp_mpf_mean <- df_bp %>%
  group_by(Nr) %>%
  summarise(mean_sys = mean(SYS),
            mean_dia = mean(DIA),
            mean_pul = mean(PUL),
            mean_mpf = mean(ManualPulseFreq))
tbl_bp_mpf_mean
```

* Fit a regression model of `SYS` on mean manual pulse frequency

```{webr-r}
# fit regression model of SYS on mean_mpf
lm_sys_mean_mpf <- lm(mean_sys ~ mean_mpf, data = tbl_bp_mpf_mean)
(smry_sys_mean_mpf <- summary(lm_sys_mean_mpf))
```

* Plot residuals

```{webr-r}
# plot fitted values versus residuals
plot(fitted(lm_sys_mean_mpf), residuals(lm_sys_mean_mpf))
```

* Fit a regression model of `DIA` on mean manual pulse frequency

```{webr-r}
# fit regression model of DIA on mean_mpf
lm_dia_mean_mpf <- lm(mean_dia ~ mean_mpf, data = tbl_bp_mpf_mean)
(smry_dia_mean_mpf <- summary(lm_dia_mean_mpf))
```

* Plot residuals

```{webr-r}
# plot fitted values versus residuals
plot(fitted(lm_dia_mean_mpf), residuals(lm_dia_mean_mpf))
```

* Fit a regression model of `PUL` on mean manual pulse frequency

```{webr-r}
# fit regression model of PUL on mean_mpf
lm_pul_mean_mpf <- lm(mean_pul ~ mean_mpf, data = tbl_bp_mpf_mean)
(smry_pul_mean_mpf <- summary(lm_pul_mean_mpf))
```

* Plot residuals

```{webr-r}
# plot fitted values versus residuals
plot(fitted(lm_pul_mean_mpf), residuals(lm_pul_mean_mpf))
```

* Ranking of the regression coefficients

```{webr-r}
# rank estimated regression coefficient
order(c(smry_sys_mean_mpf$coefficients["mean_mpf", "Estimate"],
        smry_dia_mean_mpf$coefficients["mean_mpf", "Estimate"],
        smry_pul_mean_mpf$coefficients["mean_mpf", "Estimate"]))
```


## Problem 2: Median Predictor Variables
Fit the same type of regression models, but use the median of the predictor variables instead of the mean. 


### Tasks

* Read the data

```{webr-r}
# read data to a data.frame
s_tbl_ex09_p02_path <- "https://charlotte-ngs.github.io/asmasss2024/data/20240429_bp_data.csv"
df_bp <- read.table(s_tbl_ex09_p02_path, header = T, sep = ",")
df_bp
```

* Compute median of manual pulse frequencies

```{webr-r}
# compute median values accross individuals
library(dplyr)
tbl_bp_mpf_median <- df_bp %>%
  group_by(Nr) %>%
  summarise(median_sys = median(SYS),
            median_dia = median(DIA),
            median_pul = median(PUL),
            median_mpf = median(ManualPulseFreq))
tbl_bp_mpf_median
```

* Fit a regression model of `SYS` on median manual pulse frequency

```{webr-r}
# fit regression model of SYS on median_mpf
lm_sys_median_mpf <- lm(median_sys ~ median_mpf, data = tbl_bp_mpf_median)
(smry_sys_median_mpf <- summary(lm_sys_median_mpf))
```

* Plot residuals

```{webr-r}
# plot fitted values versus residuals
plot(fitted(lm_sys_median_mpf), residuals(lm_sys_median_mpf))
```

* Fit a regression model of `DIA` on median manual pulse frequency

```{webr-r}
# fit regression model of DIA on median_mpf
lm_dia_median_mpf <- lm(median_dia ~ median_mpf, data = tbl_bp_mpf_median)
(smry_dia_median_mpf <- summary(lm_dia_median_mpf))
```

* Plot residuals

```{webr-r}
# plot fitted values versus residuals
plot(fitted(lm_dia_median_mpf), residuals(lm_dia_median_mpf))
```

* Fit a regression model of `PUL` on median manual pulse frequency

```{webr-r}
# fit regression model of PUL on median_mpf
lm_pul_median_mpf <- lm(median_pul ~ median_mpf, data = tbl_bp_mpf_median)
(smry_pul_median_mpf <- summary(lm_pul_median_mpf))
```

* Plot residuals

```{webr-r}
# plot fitted values versus residuals
plot(fitted(lm_pul_median_mpf), residuals(lm_pul_median_mpf))
```

* Ranking of the regression coefficients

```{webr-r}
# rank estimated regression coefficient
order(c(smry_sys_median_mpf$coefficients["median_mpf", "Estimate"],
        smry_dia_median_mpf$coefficients["median_mpf", "Estimate"],
        smry_pul_median_mpf$coefficients["median_mpf", "Estimate"]))
```



